package infrastructure.persistence.sqlite.mapper;

import domain.entity.Appointment;
import domain.entity.Customer;
import domain.entity.Service;
import domain.valueobject.Description;
import domain.enums.AppointmentStatus;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.List;
import java.lang.reflect.Field;
import java.math.BigDecimal;

public class AppointmentMapper 
{
    /**
     * Reschedule by combining the table data with complex objects. 
     * (Customer and Services) already searched for by the Repository.
     */
    public static Appointment toDomain(
        ResultSet rs, 
        Customer customer, 
        List<Service> services
    ) throws SQLException 
    {
        Long id = rs.getLong("id");
        
        LocalDateTime dateTime = LocalDateTime.parse(rs.getString("date_time"));
        
        String statusString = rs.getString("status");
        AppointmentStatus status = AppointmentStatus.valueOf(statusString);
        
        Description description = new Description(rs.getString("description"));

        BigDecimal totalPrice = rs.getBigDecimal("total_price");

        return new Appointment(id, customer, dateTime, status, services, description, totalPrice);
    }

    /**
     * Injects the ID generated by the database into the User entity using Reflection.
     */
    public static void injectGeneratedId(Appointment appointment, ResultSet generatedKeys) throws SQLException 
    {
        if (generatedKeys.next()) 
        {
            long generatedId = generatedKeys.getLong(1);
            try {
                Field idField = appointment.getClass().getDeclaredField("id");
                idField.setAccessible(true);
                idField.set(appointment, generatedId);
            } catch (NoSuchFieldException | IllegalAccessException e) {
                System.err.println("Reflection error when setting the generated ID: " + e.getMessage());
            }
        }
    }
}