package infrastructure.persistence.sqlite.mapper;

import domain.entity.Customer;
import domain.valueobject.Email;
import domain.valueobject.Name;
import domain.valueobject.Phone;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.lang.reflect.Field;

public class CustomerMapper 
{
    /**
     * Converts a ResultSet from the database to the Customer Domain Entity.
     */
    public static Customer toDomain(ResultSet rs) throws SQLException 
    {
        Long id = rs.getLong("id");
        Name name = new Name(rs.getString("name"));
        Phone phone = new Phone(rs.getString("phone"));
        Email email = new Email(rs.getString("email"));
        boolean isActive = rs.getInt("active") == 1;

        int totalAppointments = 0; 

        return new Customer(id, name, phone, email, totalAppointments, isActive);
    }

    /**
     * Injects the ID generated by the database into the Customer entity using Reflection.
     */
    public static void injectGeneratedId(Customer customer, ResultSet generatedKeys) throws SQLException 
    {
        if (generatedKeys.next()) 
        {
            long generatedId = generatedKeys.getLong(1);
            try {
                Field idField = customer.getClass().getDeclaredField("id");
                idField.setAccessible(true);
                idField.set(customer, generatedId);
            } catch (NoSuchFieldException | IllegalAccessException e) {
                System.err.println("Reflection error when setting the generated ID: " + e.getMessage());
            }
        }
    }
}